# A trivial change to re-run Actions
name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install frontend deps
        run: |
          cd frontend || exit 0
          npm install || true

      - name: Install backend deps
        run: |
          cd backend || exit 0
          pip install -r requirements.txt || true

      - name: Run frontend tests
        run: |
          cd frontend || exit 0
          npm test || true

      - name: Run backend tests
        run: |
          cd backend || exit 0
          pytest || true